language: python
python:
  - "2.7"
  - "nightly"
install:
  - "pip install -r requirements.txt"
notifications:
  email: 
    recipients:
      - chris.williams@bristol.ac.uk
    on_success: change
    on_failiure: always
script: nosetests